---
output: html_document
---

#Introduction

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Our intention for this project is to evaluate the predictive power of the following five regressions: Least-Squares regression, Ridge regression, Lasso regression, Principal Component regression, and Partial Least-Squares regression. We will be using a dataset where the response variable is an individual's credit card balance and the explanatory variables are an individual's characteristics (gender, income, age, etc.). Before we ran any sort of regression on the dataset, we first engaged in some exploratory data analysis by making histograms, boxplots, and summary statistics for the variables in our dataset. After this exploratory data analysis, we turned our attention to evaluating the performance of each regression.  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; We evaluated the performance of each regression by testing to see which algorithm did the best job of predicting an individual's credit card balance, given an individual's characteristics (age, income, gender, etc.). We used built in cross-validation functionality in R functions in order to divide the data into test and training sets. We then compared the mean squared error between our five regressions. Before we get into the specifics of the regression methodology though, lets first take a look at our dataset.

