---
output: html_document
---

##Conclusion 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; As one can see in the MSE table, least squares is the best performing regression from a prediction perspective. While least-squares regression seems like it would be the best regression method to use for prediction purposes, this is probably only the case for this dataset. Ridge and Lasso, thanks to their penalty on model complexity, actually usually outperform least-squares prediction in prediction. As for the dimension-reduction regression methods, this table indicates that principal component regression is significantly inferior to partial least squares regression. This is likely because, unlike principal component regression, partial least squares regression takes into account how each explanatory variable interacts with the response variable.  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; In short, while it's surprising how well least squares performed in predicting the Balance variable, least squares' excellent performance may only be particular to this dataset. We would recommend that in future prediction projects, aspiring data-scientists use a variety of regressions for prediction in order to see which one is optimal. 